id: A14904EE1
title: 'The Vajra Verses: A Prayer of the Fierce Inner Heat'
type: translation
pechas:
- IFD4E7F17
- I515EC133
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:43:54.451980
  last_modified_at: 2023-01-04 12:43:54.452001
  collections:
  - Jigme Lingpa Series
  - Works of Tibetan Masters
alignment_to_base:
  IFD4E7F17/DA1E: DD84
  I515EC133/0AC8: DD84
